theme: jekyll-theme-minimal
title: A Personal Guide
description: A listing of things I've done and what I'm working on. 
logo: https://raw.githubusercontent.com/FuzzyBunnys/A-Personal-Guide/main/11883209_10101468642460741_5789061869252032333_o.jpg
